# wallpaper {
#     monitor = eDP-2
#     fit_mode = cover,
#     path = /home/kazz4343/Pictures/Wallpapers/wallhaven-1q2p3v_2560x1440.png
# }

# wallpaper {
#     monitor = DP-2
#     fit_mode = cover,
#     path = /home/kazz4343/Pictures/Wallpapers/wallhaven-1q2p3v_2560x1440.png

# }

# wallpaper {
#     monitor = HDMI-A-1
#     fit_mode = cover,
#     path = /home/kazz4343/Pictures/Wallpapers/wallhaven-1q2p3v_2560x1440.png
# }


# preload = /home/kazz4343/Pictures/Wallpapers/wallhaven-1q2p3v_2560x1440.png

# wallpaper = eDP-2,/home/kazz4343/Pictures/Wallpapers/wallhaven-1q2p3v_2560x1440.png
# wallpaper = DP-2,/home/kazz4343/Pictures/Wallpapers/wallhaven-1q2p3v_2560x1440.png
# wallpaper = HDMI-A-1,/home/kazz4343/Pictures/Wallpapers/wallhaven-1q2p3v_2560x1440.png