
wallpaper {
    monitor = eDP-2
    fit_mode = cover,
    path = /home/kazz4343/Pictures/Wallpapers/wallhaven-p8q8pp_2560x1440.png
}

wallpaper {
    monitor = DP-2
    fit_mode = cover,
    path = /home/kazz4343/Pictures/Wallpapers/wallhaven-p8q8pp_2560x1440.png

}

wallpaper {
    monitor = HDMI-A-1
    fit_mode = cover,
    path = /home/kazz4343/Pictures/Wallpapers/wallhaven-p8q8pp_2560x1440.png
}