-- Generated by hyprmoncfg

hl.monitor({
	output = "desc:AOC Q27G42ZE 2RMRBHA035149",
	mode = "2560x1440@240.00",
	position = "-2560x0",
	scale = 1,
	sdr_min_luminance = 0.2,
	sdr_max_luminance = 80,
})

hl.monitor({
	output = "desc:BOE NE160QDM-NYJ",
	mode = "2560x1600@165.00",
	position = "0x0",
	scale = 1.33,
	sdr_min_luminance = 0.2,
	sdr_max_luminance = 80,
})

hl.monitor({
	output = "desc:GWD ARZOPA 0x56340206",
	mode = "1920x1080@144.00",
	position = "0x1203",
	scale = 1,
	sdr_min_luminance = 0.2,
	sdr_max_luminance = 80,
})
